import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Section from '../components/Section'

const Home: NextPage = () => {
  return (
    <main >

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <Section>hello</Section>
      </main>

  )
}

export default Home
